version: '3.8'

services:
  landing-page:
    build: .
    container_name: landing-vite-container
    restart: always
    ports:
      - "8080:80"  # Exponemos temporalmente en el puerto 8080 de forma local para verificar
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=host(`cloudsrv.cloud`) || host(`www.cloudsrv.cloud`)"
      - "traefik.http.routers.landing.entrypoints=web"
      - "traefik.http.services.landing.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: web  # Red compartida donde corre Traefik (si tu red se llama diferente, cámbiala aquí)